directories:
  output: dist-electron
  buildResources: assets
appId: com.kiosk.editor
productName: Kiosk Editor
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  runAfterFinish: true
  shortcutName: Kiosk Editor
  artifactName: ${productName}-Setup-${version}.${ext}
portable:
  artifactName: ${productName}-Portable-${version}.${ext}
electronVersion: 28.0.0
compression: maximum
asar: true
