directories:
  output: dist-electron
  buildResources: build
appId: com.kiosk.player
productName: Kiosk Player
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: assets/icon.ico
  sign: null
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 28.0.0
