directories:
  output: dist-electron
  buildResources: assets
appId: com.kiosk.player
productName: Kiosk Player
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
extraResources:
  - from: electron/project.json
    to: project.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: assets/icon.ico
  sign: null
  signingHashAlgorithms:
    - sha256
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  runAfterFinish: false
  installerIcon: assets/icon.ico
  uninstallerIcon: assets/icon.ico
  shortcutName: Kiosk Player
  artifactName: ${productName}-Setup-${version}.${ext}
portable:
  artifactName: ${productName}-Portable-${version}.${ext}
electronVersion: 28.0.0
compression: maximum
asar: true
